export const texts = {
  wlc: 'Welcome to WhatsApp',
  termspolicy: 'Read our Privacy Policy. Tap “Agree and continue” to ',
  terms_service: 'accept the Teams of Service.',
  agree: '  AGREE AND CONTINUE',
  from: 'from',
  facebook: 'FACEBOOK',
  enter_ph: 'Enter your phone number',
  wp_num: 'WhatsApp will need to verify your phone number. What’s my number?',
  carrier: ' Carrier charges may apply',
  next: 'NEXT',
  enter_otp: 'Enter OTP Code',
  code_send: 'Code has been send to',
  resend_code: 'Resend Code in 56 s',
  verify: 'Verify',
  whatsapp: 'WhatsApp',
  chats: 'Chats',
  status: 'Status',
  calls: 'Calls',
  chat_yet: 'You haven’t chat yet',
  start: 'Start Chatting',
  user_details: 'User Info',
  first_name: 'First Name',
  last_name: 'Last Name',
  phone: 'Phone No ',
};
