export const fontFamily = {
  regular: 'Roboto-Regular',
  bold: 'Roboto-Bold',
  italic: 'Roboto-Italic',
  black: 'Roboto-BoldItalic',
  thin_italic: 'Roboto-ThinItalic',
  thin: 'Roboto-Thin',
  semi_bold_italic: 'Roboto-SemiBoldItalic',
  semi_bold: 'Roboto-SemiBold',
  medium: 'Roboto-Medium',
  medium_italic: 'Roboto-MediumItalic',
  light: 'Roboto-Light',
  light_italic: 'Roboto-LightItalic',
  extra_lightItalic: 'Roboto-ExtraLightItalic',
  extra_light: 'Roboto-ExtraLight',
  extra_bold_italic: 'Roboto-ExtraBoldItalic',
  extra_bold: 'Roboto-ExtraBold',
  black_italic: 'Roboto-BlackItalic',
  black_font: 'Roboto-Black',
  semi_thinItalic: 'Roboto_SemiCondensed-ThinItalic',
  semi_thin: 'Roboto_SemiCondensed-Thin',
  semi_boldc_italic: 'Roboto_SemiCondensed-SemiBoldItalic',
};
