export const images = {
  wlc_img: require('./images/wlc.png'),
  settings: require('./images/settings.png'),
  dd: require('./images/dd_down.png'),
  back: require('./images/backArrow.png'),
  green: require('./images/wlc_green.png'),
  search: require('./images/search.png'),
  camera: require('./images/camera.png'),
  img_back: require('./images/img_back.png'),
  first: require('./images/first_logo.png'),
  add: require('./images/add.png'),
  add_chats: require('./images/add_chats.png'),
  back_arrow: require('./images/back.png'),
  video: require('./images/video.png'),
  phone: require('./images/phone.png'),
  emoji: require('./images/emoji.png'),
  camera2: require('./images/camera2.png'),
  payment: require('./images/payment.png'),
  mike: require('./images/mike.png'),
  attach: require('./images/attach.png'),
  meta: require('./images/meta.jpg'),
  cross: require('./images/cross_small.png'),
  send: require('./images/send.png'),
  check: require('./images/check.png'),
};
